### ISSUE TITLE
Court selector error w/ invalid address

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-MA209AProtectiveOrder#81]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `court information`
Steps to reproduce | I think it's because we were using fake addresses. error came up when I hit next after id: court information
Expected behavior | for the interview to continue
What happened instead | I got a fat error message. none of the court selectors appeared. not a map nor choices.
Other information | I will add screenshots and pdf of error and source to GitHub issue
Variable being sought | `trial_court`
Package version | `2.0.1`
Maturity target | Level 1 - this needs to be fixed to be equivalent to the blank form
Tester contact info | eleniconstantinou

**Comment by eleniconstantinou** [comment]
Error: Eror 

Error
Retry
AttributeError: 'NoneType' object has no attribute 'name'
History
Tried to load objects from file at 0.22918s
(from docassemble.ALMassachusetts:al_massachusetts.yml)
objects from file:
  - court_emails : court_emails.yml
Tried to run mandatory code at 0.25591s
scan for variables: False
mandatory: True
code: |
  set_interview_defaults # Set some things that are true on any 209A
  
  ##################### Intro screen
  al_intro_screen
  main_209A_package_intro
  nav.set_section('section_basic')  
  who_protecting_screener # We don't use this yet?  
  users[0].name.first
  plaintiff_assistant_type_obo
  if plaintiff_assistant_type in('self', 'other'):
    refer_to_advocate
  elif plaintiff_assistant_type in('parent', 'guardian'):
    plaintiff_assistant_name
    dcf_warning_given
  elif plaintiff_assistant_type == 'advocate':
    dcf_warning_given

  if who_protecting_screener == 'someone else':
    tell_user_about_first_person_questions   
    
  other_parties.there_are_any = True
  other_parties[0].name.first
  user_saw_what_to_expect

  ########################## Page 1
  nav.set_section('section_relationship')
  user_saw_relationship
  nav.set_section('section_children')
  defendant_and_plaintiff_are_parents_of_child
  plaintiff_has_children_parent_of
  children.gather()
  plaintiff_has_children_cares_for
  children_cares_for.gather()
  # relationship_to_defendant_unmarried
  
  complaint_209A_labeled_page10003 # Page 1
  nav.set_section('section_affidavit') # these are part of the affidavit really
  user_saw_abuse_explanation
  defendant_abuse_caused_physical_harm
  if no_abuse_checked:
    abuse_does_not_qualify

  ############################ Affidavit
  nav.set_section('section_affidavit')
  complaint_209A_Affidavit # Main affidavit
  # From page 1
  incident_date # Filled in with code, I think
  if plaintiff_has_minor_children:
    include_children_in_order
    A_complaint_for_protection_from_abuse_probation_copy0005 # Page 2
  # if no_abuse_checked:
  #  abuse_does_not_qualify # placeholder question not sure we even want the option of no abuse checked. Ask SMEs
    # refer_to_258E_resources # Maybe this info is wrong

  # Attach evidence
  nav.set_section('review_exhibits')
  has_evidence
  if has_evidence and has_evidence_ready_to_upload:
    review_exhibits

  nav.set_section('section_relief')
  ############################ Relief
  # From page 1
  order_defendant_stop_abuse_yes # make sure this gets defined, but it will always be True via a code block
  if not order_defendant_remain_away_plaintiff_residence_yes:
    If_this_is_an_apartment_building_or_other_multiple_family_dwelling_check_here = DAEmpty()
  order_defendant_pay_yes
  if not order_defendant_pay_yes:
    losses_caused_by_defendant = DAEmpty()
    order_defendant_pay_amount = DAEmpty()

  order_impound_plaintiff_address_residential_yes
  order_other_relief_yes
  if not order_other_relief_yes: # triggers asking about relief
    other_relief = DAEmpty()

  order_relief_ex_parte

  ####################### Child support
  nav.set_section('section_child_support')  
  if plaintiff_has_minor_children and len(children_of_both) and wants_child_support_yes:
      if not existing_order:
        Plaintiff_Affidavit_in_support_of_request_for_child_support_order0008   # Child support
      else:
        explain_no_child_support

  ############################## Defendant info
  # From page 1
  nav.set_section('section_defendant_info')
  defendantinformation209A0008_intro
  defendant_has_alias # redundant to def. information section
  
  defendantinformation209A0008

  ########################## Plaintiff info
  nav.set_section('section_your_info')
  A_Plaintiff_Confidential_Information0011
  
  nav.set_section('section_privacy')
  impoundment_intro
  if asked_for_impoundment:
    a_258e_motion_for_impoundment0019

  # Care or custody proceedings
  nav.set_section('section_care_custody')
  have_had_paternity_cases = False # We'll reevaluate below
  have_had_custody_cases  = False
  if plaintiff_has_minor_children and defendant_and_plaintiff_are_parents_of_child and len(children_of_both):
    if has_participated_custody_case or know_of_other_custody_case:
      have_had_custody_cases = True
      A_affidavit_disclosing_care_or_custody_proceedings0009 # Aff. care or custody
      for case in other_care_custody_proceedings:
        if case.case_status == "paternity":
          have_had_paternity_cases = True 
          break # One match is good enough
      if not have_had_paternity_cases:
        have_had_paternity_cases = ask_had_paternity_case  # trigger a question if we didn't answer via care/custody questions       
      # Come back to child addresses if needed          
      evaluate_child_addresses # 
  
  # From page 1
  # Other cases involving P/D but not about the children
  nav.set_section('section_cases_with_defendant')
  other_cases.gather()
  plaintiff_and_defendant_other_case_description

  nav.set_section('section_court')
  fill_in_court_name # used in aff. of care and custody
  # Make sure we don't leave any computed values empty
  # we have some that we need to set at end instead of in regular interview flow
  # because we ask them out of order
  trigger_page1_computed_values 
  if plaintiff_has_minor_children and defendant_and_plaintiff_are_parents_of_child and len(children_of_both):
    if has_participated_custody_case or know_of_other_custody_case:
      trigger_aff_care_or_custody_computed_variables
  # Most others can be asked in-line

  docket_numbers[0]
  day # Triggers date question in format for aff. of care and custody
  
  nav.set_section('section_signature')
  signature_date
  preview_209a_package

  users[0].states_above_true
  signature_fields = ['users[0].signature']
  basic_questions_signature_flow
  users[0].signature
  
  nav.set_section('section_filing')
  download_screen
Needed definition of fill_in_court_name at 0.25603s
Tried to run block at 0.25609s
(from 209A_affidavit_disclosing_care_or_custody_proceedings.yml)
code: |
  if 'District' in trial_court.name:
    trial_court.division_district_court = trial_court.division
  elif 'Superior' in trial_court.name:
    trial_court.division_superior_court = trial_court.division
  elif 'Juvenile' in trial_court.name:
    trial_court.division_juvenile_court = trial_court.division
  elif 'Probate' in trial_court.name:
    trial_court.division_family_court = trial_court.division
  elif 'Municipal' in trial_court.name: 
    trial_court.division_bmc = trial_court.division
  fill_in_court_name = True
Show variables and values
Log
Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 7546, in assemble
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8874, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "<code block>", line 128, in <module>
NameError: name 'fill_in_court_name' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/server.py", line 7498, in index
    interview.assemble(user_dict, interview_status, old_user_dict, force_question=special_question)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 7827, in assemble
    raise the_error
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 7616, in assemble
    question_result = self.askfor(missingVariable, user_dict, old_user_dict, interview_status, seeking=interview_status.seeking, follow_mc=follow_mc, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8276, in askfor
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8874, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "<code block>", line 1, in <module>

**Comment by eleniconstantinou** [comment]
Error: 
Eror 

Error
Retry
AttributeError: 'NoneType' object has no attribute 'name'
History
Tried to load objects from file at 0.22918s
(from docassemble.ALMassachusetts:al_massachusetts.yml)
objects from file:
  - court_emails : court_emails.yml
Tried to run mandatory code at 0.25591s
scan for variables: False
mandatory: True
code: |
  set_interview_defaults # Set some things that are true on any 209A
  
  ##################### Intro screen
  al_intro_screen
  main_209A_package_intro
  nav.set_section('section_basic')  
  who_protecting_screener # We don't use this yet?  
  users[0].name.first
  plaintiff_assistant_type_obo
  if plaintiff_assistant_type in('self', 'other'):
    refer_to_advocate
  elif plaintiff_assistant_type in('parent', 'guardian'):
    plaintiff_assistant_name
    dcf_warning_given
  elif plaintiff_assistant_type == 'advocate':
    dcf_warning_given

  if who_protecting_screener == 'someone else':
    tell_user_about_first_person_questions   
    
  other_parties.there_are_any = True
  other_parties[0].name.first
  user_saw_what_to_expect

  ########################## Page 1
  nav.set_section('section_relationship')
  user_saw_relationship
  nav.set_section('section_children')
  defendant_and_plaintiff_are_parents_of_child
  plaintiff_has_children_parent_of
  children.gather()
  plaintiff_has_children_cares_for
  children_cares_for.gather()
  # relationship_to_defendant_unmarried
  
  complaint_209A_labeled_page10003 # Page 1
  nav.set_section('section_affidavit') # these are part of the affidavit really
  user_saw_abuse_explanation
  defendant_abuse_caused_physical_harm
  if no_abuse_checked:
    abuse_does_not_qualify

  ############################ Affidavit
  nav.set_section('section_affidavit')
  complaint_209A_Affidavit # Main affidavit
  # From page 1
  incident_date # Filled in with code, I think
  if plaintiff_has_minor_children:
    include_children_in_order
    A_complaint_for_protection_from_abuse_probation_copy0005 # Page 2
  # if no_abuse_checked:
  #  abuse_does_not_qualify # placeholder question not sure we even want the option of no abuse checked. Ask SMEs
    # refer_to_258E_resources # Maybe this info is wrong

  # Attach evidence
  nav.set_section('review_exhibits')
  has_evidence
  if has_evidence and has_evidence_ready_to_upload:
    review_exhibits

  nav.set_section('section_relief')
  ############################ Relief
  # From page 1
  order_defendant_stop_abuse_yes # make sure this gets defined, but it will always be True via a code block
  if not order_defendant_remain_away_plaintiff_residence_yes:
    If_this_is_an_apartment_building_or_other_multiple_family_dwelling_check_here = DAEmpty()
  order_defendant_pay_yes
  if not order_defendant_pay_yes:
    losses_caused_by_defendant = DAEmpty()
    order_defendant_pay_amount = DAEmpty()

  order_impound_plaintiff_address_residential_yes
  order_other_relief_yes
  if not order_other_relief_yes: # triggers asking about relief
    other_relief = DAEmpty()

  order_relief_ex_parte

  ####################### Child support
  nav.set_section('section_child_support')  
  if plaintiff_has_minor_children and len(children_of_both) and wants_child_support_yes:
      if not existing_order:
        Plaintiff_Affidavit_in_support_of_request_for_child_support_order0008   # Child support
      else:
        explain_no_child_support

  ############################## Defendant info
  # From page 1
  nav.set_section('section_defendant_info')
  defendantinformation209A0008_intro
  defendant_has_alias # redundant to def. information section
  
  defendantinformation209A0008

  ########################## Plaintiff info
  nav.set_section('section_your_info')
  A_Plaintiff_Confidential_Information0011
  
  nav.set_section('section_privacy')
  impoundment_intro
  if asked_for_impoundment:
    a_258e_motion_for_impoundment0019

  # Care or custody proceedings
  nav.set_section('section_care_custody')
  have_had_paternity_cases = False # We'll reevaluate below
  have_had_custody_cases  = False
  if plaintiff_has_minor_children and defendant_and_plaintiff_are_parents_of_child and len(children_of_both):
    if has_participated_custody_case or know_of_other_custody_case:
      have_had_custody_cases = True
      A_affidavit_disclosing_care_or_custody_proceedings0009 # Aff. care or custody
      for case in other_care_custody_proceedings:
        if case.case_status == "paternity":
          have_had_paternity_cases = True 
          break # One match is good enough
      if not have_had_paternity_cases:
        have_had_paternity_cases = ask_had_paternity_case  # trigger a question if we didn't answer via care/custody questions       
      # Come back to child addresses if needed          
      evaluate_child_addresses # 
  
  # From page 1
  # Other cases involving P/D but not about the children
  nav.set_section('section_cases_with_defendant')
  other_cases.gather()
  plaintiff_and_defendant_other_case_description

  nav.set_section('section_court')
  fill_in_court_name # used in aff. of care and custody
  # Make sure we don't leave any computed values empty
  # we have some that we need to set at end instead of in regular interview flow
  # because we ask them out of order
  trigger_page1_computed_values 
  if plaintiff_has_minor_children and defendant_and_plaintiff_are_parents_of_child and len(children_of_both):
    if has_participated_custody_case or know_of_other_custody_case:
      trigger_aff_care_or_custody_computed_variables
  # Most others can be asked in-line

  docket_numbers[0]
  day # Triggers date question in format for aff. of care and custody
  
  nav.set_section('section_signature')
  signature_date
  preview_209a_package

  users[0].states_above_true
  signature_fields = ['users[0].signature']
  basic_questions_signature_flow
  users[0].signature
  
  nav.set_section('section_filing')
  download_screen
Needed definition of fill_in_court_name at 0.25603s
Tried to run block at 0.25609s
(from 209A_affidavit_disclosing_care_or_custody_proceedings.yml)
code: |
  if 'District' in trial_court.name:
    trial_court.division_district_court = trial_court.division
  elif 'Superior' in trial_court.name:
    trial_court.division_superior_court = trial_court.division
  elif 'Juvenile' in trial_court.name:
    trial_court.division_juvenile_court = trial_court.division
  elif 'Probate' in trial_court.name:
    trial_court.division_family_court = trial_court.division
  elif 'Municipal' in trial_court.name: 
    trial_court.division_bmc = trial_court.division
  fill_in_court_name = True
Show variables and values
Log
Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 7546, in assemble
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8874, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "<code block>", line 128, in <module>
NameError: name 'fill_in_court_name' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/server.py", line 7498, in index
    interview.assemble(user_dict, interview_status, old_user_dict, force_question=special_question)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 7827, in assemble
    raise the_error
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 7616, in assemble
    question_result = self.askfor(missingVariable, user_dict, old_user_dict, interview_status, seeking=interview_status.seeking, follow_mc=follow_mc, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8276, in askfor
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8874, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "<code block>", line 1, in <module>

**Comment by eleniconstantinou** [comment]
[error for 209A.pdf](https://github.com/SuffolkLITLab/docassemble-MA209AProtectiveOrder/files/6727696/error.for.209A.pdf)

**Comment by eleniconstantinou** [comment]
<img width="659" alt="Screen Shot 2021-06-28 at 12 05 24 PM" src="https://user-images.githubusercontent.com/65959012/123668468-23b06480-d809-11eb-8a7c-e36494d5bcca.png">

**Comment by nonprofittechy** [comment]
Just checked to verify this is not an upstream error in AssemblyLine repo--it works here: https://apps.suffolklitlab.org/run/name_change/#/15

**Comment by nonprofittechy** [comment]
This was actually fixed by @BryceStevenWilley here: https://github.com/GBLS/docassemble-MACourts/commit/442a00e6a858249218e8e6e531d360a63a02cce2 but the package wasn't installed on the test server. Good catch!
